services:
  postgres:
    image: postgres:16-alpine
    container_name: insane_barber_db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: insane_barber
      POSTGRES_PASSWORD: insane_barber_2024
      POSTGRES_DB: insane_barber
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
